apiVersion: v2
name: aimllmgemma4vllm
description: Gemma 4 26B A4B QAT-AWQ-INT4 + MTP Speculative Decoding via vLLM on RTX 5090 Blackwell
type: application
version: 2.0.7
appVersion: "2.0.7"
home: https://github.com/bayerhazard/aimighty-llmgemma4vllm
sources:
  - https://github.com/bayerhazard/aimighty-llmgemma4vllm
maintainers:
  - name: Aimighty
    email: admin@aimighty.local
